name: Feature request
description: Suggest an improvement
title: "[Feature]: "

body:
  - type: markdown
    attributes:
      value: |
        Please focus on the user problem first.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true

  - type: dropdown
    id: willingness-to-implement
    attributes:
      label: Willingness to implement
      options:
        - I can work on this
        - I can work on this with guidance
        - I cannot work on this
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context